language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  #- "3.3"  # cram does not support Python 3.3
install:
  - "pip install cram --use-mirrors"
  - "pip install . --use-mirrors"
script:
  - "cram tests/*.t"
