sudo: false
language: python

# Run tox with python 3.5, but let _it_ build the envs for the various Python
# versions (instead of Travis)
python: 3.5

env:
  matrix:
    - TOXENV=py27-piplatest
    - TOXENV=py34-piplatest
    - TOXENV=py35-piplatest
    - TOXENV=py27-pip8
    - TOXENV=py34-pip8
    - TOXENV=py35-pip8
    - TOXENV=py27-pip811
    - TOXENV=py34-pip811
    - TOXENV=py35-pip811
    - TOXENV=flake8

install:
  - travis_retry pip install tox

cache: pip

script:
  - tox
